
common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_anomalydetection'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'

dataset:
    enable: True
    dataset_name: arc_fault_example_dsk_ad
    input_data_path: 'https://software-dl.ti.com/C2000/esd/mcu_ai/01_02_00/datasets/arc_fault_dsk_anomaly_detection.zip'

data_processing_feature_extraction:
   data_proc_transforms: ['SimpleWindow', 'Downsample']
   frame_size: 1024
   sampling_rate: 100
   new_sr: 1
   variables: 1

training:
   enable: True
   model_name: 'TimeSeries_Generic_AD_17k_t'
   model_config: ''
   batch_size: 1024
   training_epochs: 250
   num_gpus: 1
   quantization: 1
   output_dequantize: true
   learning_rate: 0.0001

testing:
    enable: True
    
compilation:
    enable: True
    compile_preset_name: 'forced_soft_npu_preset'
