common:
    target_module: 'timeseries'
    task_type: 'motor_fault'
    target_device: 'MSPM0G3507'
    run_name: '{date-time}/{model_name}'

dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: motor_fault_example_dsk
    # input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_02_00/datasets/motor_fault_classification_dsk.zip

data_processing_feature_extraction:
   feature_extraction_name: MotorFault_256Input_FE_RFFT_16Feature_8Frame_3InputChannel_removeDC_2D1
#   feat_ext_transform: [ 'FFT_Q15', 'Q15_SCALE', 'Q15_MAG', 'DC_REMOVE', 'BIN_Q15', 'CONCAT']
#   frame_size: 256
#   feature_size_per_frame: 16
#   num_frame_concat: 8
#   normalize_bin: True
#   variables: 3
#   frame_skip: 1
#   store_feat_ext_data: False
#   nn_for_feature_extraction: True

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_3k_t, TimeSeries_Generic_7k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t
    model_name: 'MotorFault_model_1_t'
    model_config: ''
    batch_size: 256
    training_epochs: 30
    num_gpus: 0
    quantization_method: 'QAT'  # QAT/PTQ
    quantization: 2

testing:
    enable: True
   
compilation:
    # enable/disable compilation
    enable: True #False
    #compile_preset_name: compress_npu_layer_data, forced_soft_npu_preset  # Available only for devices with NPU









































































