common:
    target_module: 'timeseries'
    task_type: 'motor_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'

dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: 'motor_fault_example_dsk'

data_processing_feature_extraction:
    feature_extraction_name: Input256_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_2D1
#    feature_extraction_name: 'Input256_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_1D'
#    feature_extraction_name: Input256_FFT_128Feature_1Frame_3InputChannel_removeDC_2D1
    # feature_extraction_name: Input128_RAW_128Feature_1Frame_3InputChannel_removeDC_2D1
    # feature_extraction_name: 'Custom_MotorFault'
    # frame_size: 1024
    # feature_size_per_frame: 64
    # num_frame_concat: 4
    # normalize_bin: 1
    # stacking: 2D1
    # feat_ext_transform: [ 'FFT_FE', 'FFT_POS_HALF', 'DC_REMOVE', 'ABS', 'BINNING', 'LOG_DB', 'CONCAT' ]
    # offset: 0
    # scale: 1
    # frame_skip: 1
    # log_mul: 20
    # log_base: 10
    # log_threshold: 1e-100
#    store_feat_ext_data: False
#    nn_for_feature_extraction: False
    gof_test: False
    variables: 3

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_1k_t, TimeSeries_Generic_4k_t, TimeSeries_Generic_6k_t, TimeSeries_Generic_13k_t
    # GUI only model names: MotorFault_model_1_t, MotorFault_model_2_t, MotorFault_model_3_t
    model_name: 'NAS'
#    model_spec: '../tinyml-mlbackend/proprietary_models/cnn_mf_1l.py'
    model_config: ''
    batch_size: 64
    training_epochs: 10
    num_gpus: 1
    quantization_weight_bitwidth: 8
    quantization_activation_bitwidth: 8
    learning_rate: 0.1
    quantization: 1

    nas_enabled: True
    nas_epochs: 10   # num epochs for which search to be executed
    nas_optimization_mode: 'Memory' # 'Compute' 'Memory'

    # Preset mode
    nas_model_size: 's'  # 's' 'm' 'l' 'xl' 'xxl'

    # Customization mode
    # nas_nodes_per_layer: 4  # Each layer consists of few nodes for DAG construction
    # nas_layers: 3    # Minimum should be 3
    # nas_init_channels: 1    # Initial feature map channel for conv layer
    # nas_init_channel_multiplier: 3  # First layer channel multiplier
    # nas_fanout_concat: 4   # num nodes_per_layer to concat for output of current layer, it should always be less than equal to nodes_per_layer

    # load_saved_model: '/data/hdd/files/a1245511/tinyml-modelmaker/data/projects/motor_fault_example_dsk/run/tinpu-large/NAS/training/model.pt'

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: False #False
    # No preset is required for devices other than F28P55
#    compile_preset_name: forced_soft_npu_preset
