common:
  task_type: generic_timeseries_regression
  target_device: F29H85
dataset:
  dataset_name: induction_motor_speed_prediction
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/induction_motor_speed_prediction_dataset.zip
data_processing_feature_extraction:
  data_proc_transforms: ['SimpleWindow']
  variables: 11
  stride_size: 1
  feature_extraction_name: Custom_Default
  feat_ext_transform: ['ABS', 'LOG_DB', 'CONCAT']
  frame_size: 8
  feature_size_per_frame: 8
  num_frame_concat: 1
training:
  model_name: REGR_1k
  batch_size: 256
  training_epochs: 50
  num_gpus: 0
  learning_rate: 0.000001
  output_int: false
testing: {}
compilation: {}
