common:
  task_type: generic_timeseries_classification
  target_device: F28P55
dataset:
  dataset_name: esda_nilm_2021_5_variable_4_class_dataset
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/esda_nilm_2021_5_variable_4_class_dataset.zip
data_processing_feature_extraction:
  feat_ext_transform:
  - FFT_FE
  - FFT_POS_HALF
  - WINDOWING
  - BINNING
  - NORMALIZE
  - ABS
  - LOG_DB
  - CONCAT
  frame_size: 32
  feature_size_per_frame: 8
  num_frame_concat: 8
  variables: 5
training:
  model_name: CLS_13k_NPU
  model_config: ''
  batch_size: 256
  training_epochs: 15
  num_gpus: 0
  quantization: 2
  learning_rate: 0.04
  output_int: true
testing: {}
compilation:
  keep_libc_files: true
