common:
  run_name: model_performance
  target_device: F28P55
  target_module: timeseries
  task_type: generic_timeseries_classification
compilation:
  compile_preset_name: default_preset
  enable: true
  keep_libc_files: true
data_processing_feature_extraction:
  feature_extraction_name: Custom_Default
  data_proc_transforms: [SimpleWindow]
  frame_size: 128
  stride_size: 1
  variables: 1
dataset:
  dataset_name: model_performance
  enable: true
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/arc_fault_classification_dsi.zip
testing:
  enable: true
training:
  enable: true
  model_name: TimeSeries_Generic_1k_t
  batch_size: 256
  model_config: ''
  num_gpus: 0
  training_epochs: 20
