common:
  task_type: generic_timeseries_anomalydetection
  target_device: F28P55
dataset:
  dataset_name: motor_fault_example_dsk_ad
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/motor_fault_anomaly_detection_dataset.zip
data_processing_feature_extraction:
  feature_extraction_name: Input256_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_2D1
  variables: 3
  feature_size_per_frame: 4
training:
  model_name: AD_Linear
  model_config: ''
  batch_size: 50
  learning_rate: 0.001
  training_epochs: 50
  num_gpus: 1
  quantization: 1
  output_int: false
testing: {}
compilation:
  compile_preset_name: forced_soft_npu_preset
