common:
  task_type: motor_fault
  target_device: MSPM0G3507
dataset:
  dataset_name: motor_fault_example_dsk
data_processing_feature_extraction:
  feature_extraction_name: MotorFault_256Input_FE_RFFT_16Feature_8Frame_3InputChannel_removeDC_2D1
#   feat_ext_transform: [ 'FFT_Q15', 'Q15_SCALE', 'Q15_MAG', 'DC_REMOVE', 'BIN_Q15', 'CONCAT' ]
#   frame_size: 256
#   feature_size_per_frame: 16
#   num_frame_concat: 8
#   normalize_bin: True
#   variables: 3
#   frame_skip: 1
#   store_feat_ext_data: False
#   nn_for_feature_extraction: True
training:
  model_name: CLS_1k_NPU
  model_config: ''
  batch_size: 256
  training_epochs: 30
  num_gpus: 0
  quantization_method: QAT
  quantization: 2
testing: {}
compilation: {}
#  compile_preset_name: compress_npu_layer_data, forced_soft_npu_preset  # Available only for devices with NPU
