common:
    target_module: 'timeseries'
    task_type: 'arc_fault'
    target_device: 'MSPM0G5187'
    run_name: '{date-time}/{model_name}'
    
dataset:
    enable: True
    dataset_name: 'ac_arc_fault'
    input_data_path: "https://software-dl.ti.com/C2000/esd/mcu_ai/01_02_00/datasets/ac_arc_fault.zip"
    split_type: within_files
    split_factor:
      - 0.6
      - 0.2
      - 0.2
    # gof_test: True


data_processing_feature_extraction:

    feature_extraction_name: ArcFault_1024Input_FE_RFFT_128Feature_8Frame_1InputChannel_removeDC_Full_Bandwidth
    #feat_ext_transform: [ 'FFT_Q15', 'Q15_SCALE', 'Q15_MAG', 'DC_REMOVE', 'BIN_Q15', 'CONCAT']
    # frame_size: 1024
    # feature_size_per_frame: 128
    # num_frame_concat: 8
    # frame_skip: 8
    # scale: 1
    # offset: 0
    # normalize_bin: True
    # variables: 1
    # q15_scale_factor: 4
    # gof_test: True
    store_feat_ext_data: False

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_1k_t, TimeSeries_Generic_4k_t, TimeSeries_Generic_6k_t, TimeSeries_Generic_13k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t, ArcFault_model_1400_t
    model_name: 'TimeSeries_Generic_1k_t'
#    with_input_batchnorm: False
#    model_spec: '../tinyml-mlbackend/proprietary_models/cnn_af_3l.py'
    model_config: ''
    batch_size: 30
    training_epochs: 30
    num_gpus: 0
    quantization: 2
    learning_rate: 0.001
    weight_decay: 1e-5 
    # gof_test: True
 
testing:
    enable: True


compilation:
    enable: True #False