common:
  task_type: motor_fault
  target_device: F28P55
dataset:
  dataset_name: fan_blade_fault
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/fan_blade_fault_dsi.zip
data_processing_feature_extraction:
  data_proc_transforms: []
  feature_extraction_name: Input256_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_2D1
#    feature_extraction_name: Input256_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_1D
#    feature_extraction_name: Input256_FFT_128Feature_1Frame_3InputChannel_removeDC_2D1
#    feature_extraction_name: Input128_RAW_128Feature_1Frame_3InputChannel_removeDC_2D1
#    feature_extraction_name: Custom_MotorFault
#    frame_size: 256
#    feature_size_per_frame: 128
#    num_frame_concat: 8
#    normalize_bin: 1
#    stacking: 2D1
#    feat_ext_transform: [ 'FFT_FE', 'FFT_POS_HALF', 'DC_REMOVE', 'ABS', 'LOG_DB', 'CONCAT' ]
#    offset: 0
#    scale: 1
#    frame_skip: 1
#    log_mul: 20
#    log_base: 10
#    log_threshold: 1e-100
  variables: 3
training:
  model_name: CLS_4k_NPU
  model_config: ''
  batch_size: 256
  training_epochs: 20
  num_gpus: 0
testing: {}
compilation: {}
