
common:
    target_module: 'timeseries'
    task_type: 'motor_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: fan_blade_fault
    input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_02_00/datasets/fan_blade_fault_dsi.zip

data_processing_feature_extraction: # One or more can be cascaded in the list
    data_proc_transforms: []
#    feature_extraction_name: MotorFault_256Input_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_1D
    feature_extraction_name: MotorFault_256Input_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_2D1
#    feature_extraction_name: MotorFault_256Input_FFT_128Feature_1Frame_3InputChannel_removeDC_2D1
#    feature_extraction_name: MotorFault_128Input_RAW_128Feature_1Frame_3InputChannel_removeDC_2D1
#    feature_extraction_name: Custom_MotorFault
#    frame_size: 256
#    feature_size_per_frame: 128
#    num_frame_concat: 8
#    normalize_bin: 1
#    stacking: 2D1
#    feat_ext_transform: ['FFT_FE', 'FFT_POS_HALF', 'DC_REMOVE', 'ABS', 'LOG_DB', 'CONCAT']
#    offset: 0
#    scale: 1
#    frame_skip: 1
#    log_mul: 20
#    log_base: 10
#    log_threshold: 1e-100
#    store_feat_ext_data: False
#    nn_for_feature_extraction: False
    variables: 3

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_1k_t, TimeSeries_Generic_4k_t, TimeSeries_Generic_6k_t, TimeSeries_Generic_13k_t
    # GUI only model names: MotorFault_model_1_t, MotorFault_model_2_t, MotorFault_model_3_t
    model_name: 'TimeSeries_Generic_4k_t'
#    model_spec: '../tinyml-mlbackend/proprietary_models/cnn_mf_1l.py'
    model_config: ''
    batch_size: 256
    training_epochs: 20
    num_gpus: 0  # 1
#    learning_rate: 0.001

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False
    # No preset is required for devices other than F28P55. default_preset is chosen by default
#    compile_preset_name: compress_npu_layer_data, forced_soft_npu_preset  # Available only for devices with NPU
