common:
    target_module: 'vision'    
    task_type: 'image_classification'
    target_device: 'MSPM0G5187'
    run_name: '{date-time}/{model_name}'

dataset:
    enable: True
    dataset_name: 'mnist_image_classification'
    input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_02_00/datasets/mnist_classes.zip


data_processing_feature_extraction:

    feature_extraction_name: Mnist_Default
    # image_height: 28
    #image_width: 28
    # image_num_channel: 1
    # image_mean: 0.1307
    # image_scale: 0.3081
    # variables: 1

training:

    enable: True #False
    model_name: 'Lenet5'
    # dataset_loader: GenericImageDataset
    batch_size: 64
    training_epochs: 14
    num_gpus: 0
    quantization: 2
    learning_rate: 0.1
  
testing:

    enable: True


compilation:
    enable: True #False