common:
  task_type: generic_timeseries_forecasting
  target_device: F28P55
dataset:
  dataset_name: forecasting_pmsm_rotor_temp
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/pmsm_rotor_temp.zip
data_processing_feature_extraction:
  data_proc_transforms:
  - SimpleWindow  # 'SimpleWindow' must be specified for forecasting tasks
  frame_size: 3
  stride_size: 0.4
  forecast_horizon: 1  # Number of future timesteps to be predicted
  variables: 6 # takes the first 'variables' columns after the time columns as input to predict the target variables
  target_variables:
  - 5
training:
  model_name: FCST_LSTM8
  model_config: ''
  batch_size: 256
  training_epochs: 20
  num_gpus: 0
  quantization: 1
  optimizer: adam
  learning_rate: 0.005
  output_int: false
testing: {}
compilation: {}
