
common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_anomalydetection'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
dataset:
    enable: True 
    dataset_name: fan_blade_fault
    input_data_path: 'https://software-dl.ti.com/C2000/esd/mcu_ai/01_02_00/datasets/fan_blade_ad_dataset.zip'
    split_type: 'within_files'
    split_factor: [0.6, 0.1, 0.3]

data_processing_feature_extraction: 
    data_proc_transforms: []
    #the length of input feature_size for the model should multiples of 2 for now. 
    feature_extraction_name: MotorFault_256Input_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_2D1
    variables: 3
    num_frame_concat: 4
    stride_size: 0.5


training:
    enable: True 
    model_name: 'TimeSeries_Generic_AD_17k_t'
    model_config: ''
    batch_size: 64
    training_epochs: 200
    num_gpus: 0
    learning_rate: 0.001
    quantization: 2
    output_dequantize: True

testing:
    enable: True

compilation:
    enable: True 
