
common:
    target_module: 'timeseries'
    task_type: 'arc_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
dataset:
    # enable/disable dataset loading
    enable: True
    dataset_name: arc_fault_example_dsi
#    split_names: [training, validation]
    
data_processing_feature_extraction:
    data_proc_transforms: [Downsample, SimpleWindow]
    gain_variations: {arc: [0.9, 1.1], normal: [0.8, 1.2]}
    # Downsample
    sampling_rate: 313000
    new_sr: 3130
    # SimpleWindow
    frame_size: 256
    stride_size: 0.01

    variables: 1
    gof_test: False

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_1k_t, TimeSeries_Generic_4k_t, TimeSeries_Generic_6k_t, TimeSeries_Generic_13k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t
    model_name: 'TimeSeries_Generic_13k_t'
    # model_spec: '../tinyml-mlbackend/proprietary_models/cnn_af_3l.py'
    model_config: ''
    batch_size: 2048
    training_epochs: 10
    num_gpus: 0

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False
#    compile_preset_name: default_preset/forced_soft_npu_preset
