
common:
    target_module: 'timeseries'
    task_type: 'pir_detection'
    target_device: 'CC2755'
    run_name: '{date-time}/{model_name}'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: pir_detection
    input_data_path: /home/a0500425/ti_edge_ai_studio/pir_detection_classification_dsk.zip # add path here

data_processing_feature_extraction: # One or more can be cascaded in the list
    data_proc_transforms: []
    feature_extraction_name: PIRDetection_125Input_25Feature_25Frame_1InputChannel_2D
    variables: 3

training:
    # enable/disable training
    enable: True #False
    model_name: 'PIRDetection_model_1_t'
    model_config: ''
    batch_size: 64
    training_epochs: 50
    num_gpus: 0  # 1
#    learning_rate: 0.001

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False
    # No preset is required for devices other than F28P55. default_preset is chosen by default
#    compile_preset_name: compress_npu_layer_data, forced_soft_npu_preset  # Available only for devices with NPU
