
common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_classification'
    target_device: 'MSPM0G5187'
    run_name: '{date-time}/{model_name}'

dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: ecg_classification_4class
    input_data_path: "https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/ecg_classification_4class.zip"

data_processing_feature_extraction:
    feature_extraction_name: ECG2500Input_Roundoff_1Frame
    # feat_ext_transform: ['ECG_NORMALIZE']
    # frame_size: 2500
    # feature_size_per_frame: 16
    # num_frame_concat: 8
    # frame_skip: 1
    # offset: 0
    # scale:1
    # variables: 1
    # q15_scale_factor: 5
    # normalize_bin: True


training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: CLS_1k_NPU, CLS_4k_NPU, CLS_6k_NPU, CLS_13k_NPU
    model_name: 'CLS_55k_NPU'
#    model_spec: ''
    batch_size: 12
    learning_rate: 0.001
    weight_decay: 4e-5
    optimizer: 'adam'
    training_epochs: 25
    num_gpus: 0

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False
