common:
  task_type: arc_fault
  target_device: F28P55
dataset:
  dataset_name: dc_arc_fault_example_dsk
data_processing_feature_extraction:
  feature_extraction_name: FFT1024Input_256Feature_1Frame_Full_Bandwidth
#   feature_extraction_name: FFT1024Input_256Feature_1Frame_Half_Bandwidth
#   feature_extraction_name: FFT1024Input_64Feature_4Frame_Half_Bandwidth
#   feature_extraction_name: FFT1024Input_32Feature_8Frame_Quarter_Bandwidth
#   feature_extraction_name: Custom_ArcFault
#   feat_ext_transform: [ 'FFT_FE', 'FFT_POS_HALF', 'WINDOWING', 'BINNING', 'NORMALIZE', 'ABS', 'LOG_DB', 'CONCAT' ]
#   frame_size: 1024
#   feature_size_per_frame: 128
#   num_frame_concat: 1
#   min_bin: 4
#   analysis_bandwidth: 1
#   frame_skip: 1
  variables: 1
training:
  model_name: CLS_1k_NPU
  model_config: ''
  batch_size: 32
  training_epochs: 10
  num_gpus: 0
testing:
  skip_train: false
compilation: {}
#    compile_preset_name: compress_npu_layer_data, forced_soft_npu_preset  # Available only for devices with NPU
