common:
  task_type: generic_timeseries_anomalydetection
  target_device: F28P55
dataset:
  dataset_name: ecg_ad
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/ecg_ad_dataset.zip
  split_type: amongst_files
  split_factor:
  - 0.6
  - 0.1
  - 0.3
data_processing_feature_extraction:
  data_proc_transforms:
  - SimpleWindow
  feat_ext_transform:
  - FFT_FE
  - FFT_POS_HALF
  - ABS
  - DC_REMOVE
  frame_size: 140
  variables: 1
training:
  model_name: AD_Linear
  model_config: ''
  batch_size: 64
  learning_rate: 0.001
  training_epochs: 200
  num_gpus: 1
  quantization: 1
  output_int: false
testing: {}
compilation:
  compile_preset_name: forced_soft_npu_preset
