common:
    target_module: 'timeseries'
    task_type: 'arc_fault'
    target_device: 'F28P55'
    run_name: 'running_model_on_device'

dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: dc_arc_fault_example_dsk
#    split_type: within_files

data_processing_feature_extraction:
    # One or more can be cascaded in the list
    # transforms: 'DownSample SimpleWindow'
    data_proc_transforms: []
    # Downsample
    #sampling_rate: 313000
    #new_sr: 3130
    # SimpleWindow
    #frame_size: 256
    #stride_size: 0.01

    feature_extraction_name: FFT1024Input_256Feature_1Frame_Full_Bandwidth
#   feature_extraction_name: FFT1024Input_256Feature_1Frame_Half_Bandwidth
#   feature_extraction_name: FFT1024Input_64Feature_4Frame_Half_Bandwidth
#   feature_extraction_name: FFT1024Input_32Feature_8Frame_Quarter_Bandwidth
    variables: 1

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_1k_t, TimeSeries_Generic_4k_t, TimeSeries_Generic_6k_t, TimeSeries_Generic_13k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t, ArcFault_model_1400_t
    model_name: 'TimeSeries_Generic_1k_t'
    model_config: ''
    batch_size: 32
    training_epochs: 10
    num_gpus: 0
    quantization_weight_bitwidth: 2

testing:
    enable: True
    skip_train: False  # True if only the model needs to be tested (BYOM for testing). model_path below needs to be given

compilation:
    # enable/disable compilation
    enable: True #False
