common:
  task_type: generic_timeseries_regression
  target_device: F28P55
dataset:
  dataset_name: torque_measurement
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_03_00/datasets/torque_measurement_dataset.zip
data_processing_feature_extraction:
  data_proc_transforms:
  - SimpleWindow
  variables: 10
  frame_size: 128
  stride_size: 0.25
training:
  model_name: REGR_10k
  batch_size: 512
  training_epochs: 50
  num_gpus: 0
  learning_rate: 0.001
  output_int: false
testing: {}
compilation: {}
