common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_regression'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
    
dataset:
    # enable/disable dataset loading
    enable: True
    data_dir: 'files'
    dataset_name: 'washing_machine'
    input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_02_00/datasets/washing_machine_load_dataset.zip
#    split_names: [training, validation]

data_processing_feature_extraction: # One or more can be cascaded in the list
    # transforms: 'DownSample SimpleWindow'
    data_proc_transforms: []
    # Downsample
    sampling_rate: 1
    #new_sr: 1
    # SimpleWindow
    stride_size: 0.1
    feat_ext_transform: ['SimpleWindow']
    frame_size: 256
    feature_size_per_frame: 256
    # num_frame_concat: 1
    # normalize_bin: 1
    # stacking: 1D

    offset: 0
    scale: 1
    # frame_skip: 1
    log_mul: 20
    log_base: 10
    log_threshold: 1e-100
    variables: 6

training:
    # enable/disable training
    enable: True #False
    optimizer: 'adam'
    lr_scheduler: 'cosineannealinglr'
    # F28x generic timeseries regression models :'TimeSeries_Generic_Regr_10k_t','TimeSeries_Generic_Regr_3k_t',
    model_name: 'Reg_Washing_Machine_13K_t' # 'Reg_Washing_Machine_4K_t'
    model_config: ''
    batch_size: 128
    training_epochs: 200
    lambda_reg : 0.01
    num_gpus: 1
    quantization: 0
    # output_dequantize : True

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False
    # No preset is required for devices other than F28P55. default_preset is chosen by default
#    compile_preset_name: compress_npu_layer_data, forced_soft_npu_preset  # Available only for devices with NPU
